# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml requirements.txt ./

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       gcc libxml2-dev libxslt1-dev libffi-dev python3-dev build-essential \
    && pip install --no-cache-dir -r requirements.txt \
    && rm -rf /var/lib/apt/lists/*

COPY . .

CMD ["python", "run_server.py"]
