# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    git gcc libpq-dev && rm -rf /var/lib/apt/lists/*

# Copy requirements and pyproject
COPY requirements.txt pyproject.toml .

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project
COPY . .

# Install the MCP server package
RUN pip install --no-cache-dir .

# Default command to start the MCP server
CMD ["python", "run_server.py"]
