# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Academic Scraper MCP Server
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Prevent Python from buffering stdout/stderr
ENV PYTHONUNBUFFERED=1

# Install system dependencies (Chromium for headless scraping)
RUN apt-get update && apt-get install -y --no-install-recommends \
    chromium \
    chromium-driver \
 && rm -rf /var/lib/apt/lists/*

# Copy dependency files and install Python dependencies
COPY pyproject.toml requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the source code
COPY . .

# Expose port if needed (not needed for stdio)

# Default command to start the MCP server
CMD ["python", "run_server.py"]
